import {Renderer,W,H} from './renderer.js';
import {initPuzzles} from './puzzles-v2.js';
const $=id=>document.getElementById(id),SAVE='bruma-v2.1',VERSION='2.1';
const initial=()=>({version:VERSION,scene:'harbor',x:355,face:1,inventory:[],flags:{},notes:['case'],visited:{},mirrors:[0,0,1,1,0,1,0,1,0],language:'es',lamp:{x:370,y:320,z:135,pinned:false,color:0},exposure:1.55,hints:{}});
let state=initial(),stored=null;try{const data=JSON.parse(localStorage.getItem(SAVE));if(data?.version===VERSION&&['harbor','tavern','archive','lighthouse'].includes(data.scene)&&Array.isArray(data.inventory)){stored=data;state={...initial(),...data};}}catch{}
const t=(es,en)=>state.language==='es'?es:en;
let renderer,puzzles,playing=false,selected=null,verb='interact',hover=null,showZones=false,noticeTimer,pending=null,tx=state.x,moving=false,walkPhase=0,lastTime=0,modalTick=null,previousFocus=null;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const objects={},spriteInfo={};
const cat={name:'cat-look',height:143,foot:677};
const SCENES={
 harbor:{title:['Aduana de lo ausente','Customs of the absent'],npc:'celso',npcX:638,npcH:188,foot:646,ambient:[.47,.52,.66],lights:[{p:[234,370,85],c:[3.4,1.5,.48],r:630},{p:[1240,165,165],c:[.4,1.25,2.8],r:1140},{p:[715,625,160],c:[.55,.3,.16],r:710}]},
 tavern:{title:['La Última Luz','The Last Light'],npc:'lua',npcX:950,npcH:259,foot:652,ambient:[.37,.38,.47],lights:[{p:[1197,254,105],c:[2.6,1.35,.5],r:1000},{p:[260,248,180],c:[.22,1.1,2.1],r:750},{p:[594,317,75],c:[1.4,.58,.28],r:500}]},
 archive:{title:['Archivo de las mareas','The tidal archive'],npc:'ofelia',npcX:777,npcH:229,foot:645,ambient:[.37,.38,.5],lights:[{p:[660,244,140],c:[.3,1.95,2.7],r:1000},{p:[338,390,100],c:[2.65,1.45,.55],r:670},{p:[1196,281,75],c:[1.4,.55,1.5],r:520}]},
 lighthouse:{title:['La cámara del faro','The lantern room'],npc:null,ambient:[.3,.36,.53],lights:[{p:[440,173,145],c:[2.4,.35,.2],r:810},{p:[784,198,150],c:[.25,.7,2.2],r:810},{p:[640,120,160],c:[.3,1.5,.6],r:740}]}
};
const items={
 calco:{icon:'◈',name:['Calco del sello','Seal rubbing'],desc:['La muesca queda abajo. Un defecto de fabricación ascendido a patrimonio municipal.','The nick is at the bottom. A manufacturing defect promoted to municipal heritage.']},
 filtro:{icon:'◐',name:['Filtro de Lúa','Lúa’s filter'],desc:['Ámbar para la tinta roja; cian para la azul. No cambia lo escrito: cambia lo que alcanzas a ver.','Amber for red ink; cyan for blue. It changes what you can see, not what was written.']},
 barco:{icon:'♧',name:['Barco de papel','Paper boat'],desc:['Flota la mitad de bien que una factura y el doble que mi dignidad. Tiene letras por dentro.','It floats half as well as an invoice and twice as well as my dignity. There is writing inside.']},
 contrato:{icon:'▤',name:['Contrato de sombra','Shadow contract'],desc:['Dos tintas, dos versiones de una misma firma. El cian conserva el derecho de revisión.','Two inks, two versions of the same signature. Cyan preserves the right of review.']},
 prueba:{icon:'≋',name:['Prueba de alteración','Evidence of alteration'],desc:['La copia intermedia recibió una segunda escritura. La presión delata lo que la tinta disimula.','The middle copy was written on a second time. Pressure betrays what ink conceals.']},
 llave:{icon:'⚿',name:['Llave del faro','Lighthouse key'],desc:['Funciona con cerraduras y con expectativas razonables.','Works on locks and reasonable expectations.']},
 prisma:{icon:'◇',name:['Prisma testigo','Witness prism'],desc:['Rojo: oeste-centro. Verde: este-centro. Azul: norte-oeste. Cada haz debe alcanzar su testigo.','Red: west-centre. Green: east-centre. Blue: north-west. Every beam must reach its witness.']}
};
const notes={
 case:['Mi sombra se ha marchado','My shadow has left','A medianoche dejé de proyectar sombra. El faro sigue encendido por dentro. Celso vigila su acceso.','At midnight I stopped casting a shadow. The lighthouse is still lit inside. Celso guards the way.'],
 seal:['La marca del suelo','The floor mark','Celso recuerda un golpe: el sello auténtico tiene la muesca a las seis. Los grabados se leen con luz baja, no de frente.','Celso remembers a fall: the genuine seal has a nick at six o’clock. Engravings need low, grazing light.'],
 rubbing:['Un defecto auténtico','An authentic defect','He identificado el sello con la muesca inferior. Lúa puede usar el calco para calibrar su filtro.','I identified the seal with the lower nick. Lúa can calibrate her filter from the rubbing.'],
 optics:['Lo que la luz no cuenta','What light does not tell','El filtro de Lúa alterna blanco, ámbar y cian. El barco de la taberna tiene texto escondido por dentro.','Lúa’s filter switches between white, amber and cyan. The tavern’s paper boat has hidden writing inside.'],
 amber:['La versión conveniente','The convenient version','Bajo ámbar: «Cesión voluntaria de la sombra. Duración: indefinida». La firma está ahí.','Under amber: “Voluntary assignment of the shadow. Duration: indefinite.” The signature is there.'],
 cyan:['La cláusula que falta','The missing clause','Bajo cian: «Toda cesión puede revisarse en el Archivo; ninguna firma sustituye el consentimiento». Celso no puede denegar una revisión.','Under cyan: “Every assignment may be reviewed at the Archive; no signature replaces consent.” Celso cannot deny a review.'],
 copies:['Papel con memoria','Paper with a memory','Ofelia explica el papel de copia: un solo trazo atraviesa A, B y C con presiones 3, 2 y 1. Una segunda escritura deja otra profundidad.','Ofelia explains carbon copies: a single stroke passes through A, B and C with pressures 3, 2 and 1. A second writing leaves a different depth.'],
 fraud:['La segunda escritura','The second writing','Las marcas son 3, 3 y 1. B debería ser 2. Alguien reescribió «hasta el alba» como «indefinida».','The marks are 3, 3 and 1. B should be 2. Someone rewrote “until dawn” as “indefinite”.'],
 truth:['No era un secuestro','It was not a kidnapping','Ofelia alteró la duración para que la sombra no tuviera que regresar. La protegió, pero decidió por ella.','Ofelia altered the duration so the shadow would not have to return. She protected her, but made her decision for her.'],
 beams:['La declaración de luz','A testimony of light','El prisma indica los testigos: rojo al oeste-centro, verde al este-centro, azul al norte-oeste. Los haces obedecen a los espejos. La sombra hablará cuando los tres lleguen.','The prism marks the witnesses: red west-centre, green east-centre, blue north-west. Beams obey mirrors. The shadow will speak when all three arrive.'],
 freedom:['Una voz, no una propiedad','A voice, not a possession','He escuchado a mi sombra. No quería otra dueña ni otra protectora. Quería poder elegir.','I listened to my shadow. She did not want another owner or another protector. She wanted a choice.']
};
function note(s,duration=5200){clearTimeout(noticeTimer);$('notice').textContent=s;$('notice').classList.add('visible');noticeTimer=setTimeout(()=>$('notice').classList.remove('visible'),duration);}
function save(){if(!playing)return;state.x=Math.round(state.x);try{localStorage.setItem(SAVE,JSON.stringify(state));}catch{}}
function remember(id){if(!state.notes.includes(id)){state.notes.push(id);note(t('Anotado en el cuaderno.','Added to your notebook.'),2200);}save();}
function add(id){if(!state.inventory.includes(id))state.inventory.push(id);ui();save();}
function remove(id){state.inventory=state.inventory.filter(x=>x!==id);if(selected===id)selected=null;ui();save();}
function flag(id,v=true){state.flags[id]=v;save();}
function has(id){return state.inventory.includes(id);}
function button(text,fn,className=''){const b=document.createElement('button');b.textContent=text;if(className)b.className=className;b.onclick=fn;return b;}
function modal(title,body='',wide=false){closeDialogue();pending=null;tx=state.x;modalTick=null;previousFocus=document.activeElement;$('overlay').hidden=false;$('panel').className=wide?'wide':'';$('panel').innerHTML='<div class="panel-top"><div><div class="eyebrow">BRUMA · '+t('Cuestiones pendientes','Unfinished business')+'</div><h2 id="panel-title"></h2></div><button class="close" aria-label="'+t('Cerrar','Close')+'">×</button></div><div id="panel-content"></div>';$('panel-title').textContent=title;$('panel-content').innerHTML=body;$('panel').querySelector('.close').onclick=closeModal;$('panel').querySelector('.close').focus();return $('panel-content');}
function closeModal(){modalTick=null;$('overlay').hidden=true;previousFocus?.focus?.();save();}
function closeDialogue(){$('dialogue').hidden=true;save();}
function say(name,line,choices=[]){selected=null;pending=null;tx=state.x;$('overlay').hidden=true;modalTick=null;$('dialogue').hidden=false;$('speaker').textContent=name;$('line').textContent=line;$('choices').replaceChildren();for(const [label,fn] of choices)$('choices').append(button(label,()=>{closeDialogue();fn?.();}));if(!choices.length)$('choices').append(button(t('Continuar','Continue'),closeDialogue));$('choices').querySelector('button')?.focus();}
function exchange(name,line,npc){say(name,line,[[t('Seguir hablando.','Keep talking.'),()=>talk(npc)],[t('Hasta ahora.','See you.'),()=>{}]]);}
function talk(npc){
 state.visited[npc]=(state.visited[npc]||0)+1;save();
 if(npc==='celso'){
  const options=[
   [t('He perdido mi sombra.','I have lost my shadow.'),()=>{remember('seal');exchange('Celso',t('«Perdida» es ventanilla tres. «Fugada», ventanilla cuatro. Aquí solo tenemos una ventanilla, por recortes.\nLúa sabe de sombras. Para calibrar su filtro necesita el sello auténtico: en la placa hay cuatro. El mío se cayó al suelo. La muesca quedó a las seis.','“Lost” is counter three. “Escaped” is counter four. We only have one counter, owing to cuts.\nLúa knows shadows. To calibrate her filter she needs the genuine seal, one of four on the plaque. Mine fell on the floor. The nick is at six o’clock.'),'celso');}],
   [t('¿Por qué llevas una tetera?','Why are you wearing a teapot?'),()=>exchange('Celso',t('Porque una concha es vivienda y una tetera, ajuar. El ajuar no tributa.\nAntes era de mi mujer. Ella decía que no era una casa pequeña, sino una excusa para estar cerca. Ahora sobra sitio.','Because a shell is property and a teapot is household goods. Household goods are not taxed.\nIt used to be my wife’s. She said it was not a small house, just an excuse to stay close. There is too much room now.'),'celso')],
   [t('¿Proteges el puerto o tu puesto?','Are you protecting the harbour or your job?'),()=>exchange('Celso',t('El último al que dejé pasar no volvió. Mi superior dijo que debí pedir otra copia. Nadie me dijo qué hacer con la primera.\nEs fácil burlarse de un formulario. A veces es lo único que te dejan sujetar.','The last one I let through never returned. My superior said I should have asked for another copy. No one told me what to do with the first.\nForms are easy to mock. Sometimes they are the only thing you are allowed to hold on to.'),'celso')]
  ];
  if(has('contrato'))options.unshift([t('El contrato reconoce el derecho de revisión.','The contract recognises the right of review.'),()=>give('contrato','celso')]);
  if(state.flags.archiveOpen)options.unshift([t('Voy al archivo.','I am going to the archive.'),()=>go('archive',590)]);
  options.push([t('No declararé nada sin mi abogada. Es una planta.','I will say nothing without my lawyer. She is a plant.'),()=>note(t('Celso: «Especialista en recursos, supongo».','Celso: “A specialist in growing appeals, I presume.”'))]);
  say('Celso · '+t('Inspector de ausencias','Inspector of absences'),state.flags.archiveOpen?t('La cancela está abierta. No lo llames favor: si lo anoto como favor tengo que justificarlo.','The gate is open. Do not call it a favour: favours require an explanation.'):t('Nombre, especie y motivo por el que su sombra no coincide con usted. En ese orden: el impreso no admite suspense.','Name, species and reason your shadow does not match you. In that order: the form does not allow suspense.'),options);
 }
 if(npc==='lua'){
  const options=[
   [t('¿Por qué una polilla fabrica focos?','Why does a moth build spotlights?'),()=>exchange('Lúa',t('Por el mismo motivo que otros abren bares: mejor cobrar por el problema.\nEn el teatro me dijeron que tenía un talento natural para buscar la luz. No preguntaron si sabía apartarme de ella.','For the same reason others open bars: better to charge for the problem.\nAt the theatre they said I had a natural talent for finding the light. They never asked whether I knew how to step away.'),'lua')],
   [t('¿Qué ocurrió en aquel teatro?','What happened at that theatre?'),()=>exchange('Lúa',t('Apunté un foco a una actriz que quería pasar inadvertida. El público aplaudió. Ella no volvió.\nDesde entonces pregunto antes de iluminar. Casi todos los demás siguen llamándolo «dar visibilidad».','I pointed a spotlight at an actress who wanted to go unnoticed. The audience applauded. She never returned.\nNow I ask before lighting someone. Almost everyone else still calls it “giving visibility”.'),'lua')],
   [t('Necesito ver qué le hicieron a mi sombra.','I need to see what they did to my shadow.'),()=>{remember('optics');exchange('Lúa',has('filtro')?t('El barco del taburete está doblado con un contrato. Ponlo bajo el proyector. Mira las dos tintas: ámbar y cian.\nY una cosa: ver una firma no equivale a entender por qué se firmó.','The boat on the stool is folded from a contract. Put it under the projector. Read both inks: amber and cyan.\nAnd remember: seeing a signature does not mean understanding why it was signed.'):t('Mi filtro necesita una referencia de relieve. Consigue un calco del sello auténtico de la aduana. El grabado se lee con una luz baja, de lado.\nNo hace falta frotar al inspector. Lo intentaron y ahora es una tasa.','My filter needs a relief reference. Get a rubbing of the genuine customs seal. Use low light from the side to read it.\nYou do not need to rub the inspector. Someone tried; now there is a fee.'),'lua');}]
  ];
  if(has('calco')&&!has('filtro'))options.unshift([t('Te traigo el calco.','I brought the rubbing.'),()=>give('calco','lua')]);
  options.push([t('Te dejo trabajar.','I will let you work.'),()=>{}]);
  say('Lúa · '+t('Iluminadora a su pesar','A reluctant lighting engineer'),has('filtro')?t('La luz no dice la verdad. Solo hace que mentir cueste más.','Light does not tell the truth. It just makes lying more expensive.'):t('Cierra al entrar. No por la corriente: por la clientela con alas.','Close the door behind you. Not because of the draught. Because of the winged clientele.'),options);
 }
 if(npc==='ofelia'){
  const options=[
   [t('Quiero revisar este contrato.','I want this contract reviewed.'),()=>{remember('copies');exchange('Ofelia',t('Original, archivo y recibo. El papel carbón conserva un trazo con tres profundidades: 3, 2 y 1.\nSi alguien vuelve a escribir en una copia, altera esa progresión. Mira las marcas de presión del registro con la luz rasante. La tinta puede mentir; la hendidura tiene menos imaginación.','Original, archive and receipt. Carbon paper preserves a stroke at three depths: 3, 2 and 1.\nWriting on a copy again changes that progression. Inspect the pressure marks under grazing light. Ink can lie; indentations have less imagination.'),'ofelia');}],
   [t('¿Archivas recuerdos o los escondes?','Do you archive memories or hide them?'),()=>exchange('Ofelia',t('Depende de quién venga a buscarlos. Un recuerdo puede ser un refugio para alguien y una dirección para su perseguidor.\nEl catálogo insiste en que solo hay dos categorías: prestado y disponible. Un sistema muy limpio para un mundo bastante sucio.','That depends on who is looking. A memory can be a refuge for one person and an address for their pursuer.\nThe catalogue insists there are just two categories: on loan and available. A very tidy system for a rather messy world.'),'ofelia')],
   [t('¿Ocho brazos no dan ventaja con el papeleo?','Do eight arms not help with paperwork?'),()=>exchange('Ofelia',t('Ocho brazos, ocho firmas, ocho responsabilidades. Desde que pusieron el registro digital también tengo ocho contraseñas olvidadas.','Eight arms, eight signatures, eight responsibilities. Since they digitised the archive I also have eight forgotten passwords.'),'ofelia')]
  ];
  if(has('prueba')&&!has('llave'))options.unshift([t('Sé qué copia reescribiste.','I know which copy you rewrote.'),()=>give('prueba','ofelia')]);
  if(has('llave'))options.unshift([t('¿Cómo funciona el prisma?','How does the prism work?'),()=>{remember('beams');exchange('Ofelia',t('Tres entradas, tres testigos. Rojo al oeste-centro; verde al este-centro; azul al norte-oeste. Cada espejo gira el haz noventa grados.\nNo busques una contraseña. Haz que la luz llegue.','Three inputs, three witnesses. Red west-centre; green east-centre; blue north-west. Each mirror turns a beam ninety degrees.\nDo not look for a password. Make the light arrive.'),'ofelia');}]);
  options.push([t('Me llevaré solo mis conclusiones.','I will take only my conclusions.'),()=>{}]);
  say('Ofelia · '+t('Conservadora de lo inconveniente','Keeper of inconvenient things'),t('Aquí no se pierde nada. A veces se archiva con tanta precisión que nadie vuelve a encontrarlo.','Nothing is lost here. Sometimes it is filed so precisely that no one ever finds it again.'),options);
 }
}
function give(item,target){
 selected=null;
 if(item==='calco'&&target==='lua'){add('filtro');remember('optics');say('Lúa',t('Muesca abajo. Perfecto. Un filtro calibrado, cortesía de la casa.\nÁmbar y cian separan las tintas. El barquito del taburete me llegó del faro. Lo doblé porque leerlo de frente me dio náuseas.','Nick at the bottom. Perfect. One calibrated filter, on the house.\nAmber and cyan separate the inks. The paper boat on the stool came from the lighthouse. I folded it because reading it flat made me nauseous.'),[[t('Gracias. Eso explica la navegabilidad.','Thank you. That explains its seaworthiness.'),()=>{}]]);return;}
 if(item==='barco'&&target==='projector'){if(!has('filtro'))return note(t('La tinta se mezcla bajo luz blanca. Lúa puede calibrar un filtro.','The inks overlap under white light. Lúa can calibrate a filter.'));return puzzles.contract();}
 if(item==='contrato'&&target==='celso'){flag('archiveOpen');say('Celso',t('«Derecho de revisión». Está escrito en cian: la tinta de las cosas que preferían que no leyéramos.\nLa cancela está abierta. Si preguntan, usted no ha pasado. Ha iniciado un procedimiento al otro lado.','“Right of review.” Written in cyan: the ink for things they would rather we did not read.\nThe gate is open. If anyone asks, you did not pass through. You began a procedure on the other side.'),[[t('Una distinción preciosa y completamente inútil.','A beautiful and completely useless distinction.'),()=>{}]]);ui();return;}
 if(item==='prueba'&&target==='ofelia'){
  remember('truth');say('Ofelia',t('Sí. Fui yo. Cambié «hasta el alba» por «indefinida». Ella quería irse y el contrato la obligaba a volver.\nNo quería que otro documento decidiera por ella. Es una defensa bastante mala de lo que hice, ahora que lo digo en voz alta.','Yes. It was me. I changed “until dawn” to “indefinite”. She wanted to leave and the contract forced her back.\nI did not want another document deciding for her. Now that I say it aloud, it is a rather poor defence of what I did.'),[
   [t('La protegiste, pero tampoco le preguntaste.','You protected her, but you did not ask her either.'),()=>{flag('compassion');releaseKey();}],
   [t('El fraude sigue siendo fraude. Dame la llave.','Fraud is still fraud. Give me the key.'),releaseKey],
   [t('¿Y si la dejamos decidir ahora?','What if we let her decide now?'),()=>{flag('compassion');releaseKey();}]
  ]);return;
 }
 if(item==='llave'&&target==='stairs')return go('lighthouse',350);
 if(item==='prisma'&&target==='optics'){flag('prismInstalled');remember('beams');ui();return puzzles.mirrors();}
 if(item==='contrato'&&target==='projector')return puzzles.contract();
 note(t('No encajan. No todo el mundo quiere que le enseñe lo que llevo en los bolsillos.','They do not go together. Not everyone wants to see what is in my pockets.'));ui();
}
function releaseKey(){add('llave');add('prisma');remember('beams');say('Ofelia',t('Toma la llave. Y el prisma testigo. Tres haces a tres receptores; así el faro dejará que la sombra hable por sí misma.\nNunca había pensado que «conservar» también pudiera significar «no soltar».','Take the key. And the witness prism. Three beams to three receivers; then the lighthouse will let the shadow speak for herself.\nI had never considered that “preserving” could also mean “not letting go”.'),[[t('Voy a escucharla.','I am going to listen.'),()=>{}]]);}
function finish(){if(!state.flags.beams)return note(t('La cápsula retiene su voz. El prisma necesita a sus tres testigos.','The capsule holds her voice. The prism needs all three witnesses.'));remember('freedom');say(t('La sombra de Bagheera','Bagheera’s shadow'),t('No me perdí. Me fui.\nTú podías cerrar los ojos y descansar. Yo tenía que seguir siendo la prueba de que estabas allí. El faro me ofreció una noche sin tener que pertenecerle a nadie.\nLuego descubrí la letra pequeña. Supongo que eso también es bastante tuyo.','I did not get lost. I left.\nYou could close your eyes and rest. I had to keep being proof that you were there. The lighthouse offered me a night without belonging to anyone.\nThen I discovered the small print. I suppose that is rather like you too.'),[
 [t('Te estaba buscando, no reclamando. ¿Qué quieres tú?','I was looking for you, not claiming you. What do you want?'),()=>ending(0)],
 [t('Volvamos, pero sin obligación de seguirme.','Let us go home, without any obligation to follow me.'),()=>ending(1)],
 [t('Eres mi sombra. Quiero que vuelvas.','You are my shadow. I want you back.'),()=>ending(2)]
 ]);}
function ending(which){flag('ending',which+1);const endings=[
 [t('Una noche por cuenta propia','A night of her own'),t('La sombra no vuelve a tus patas. Sale por la ventana y se queda un momento sobre el mar, sin dueño y sin prisa.\nCelso inventará una casilla para eso. Lúa apagará un foco. Ofelia dejará un hueco en el catálogo.\nY tú, por primera vez, no confundes estar sola con que te falte algo.','The shadow does not return to your paws. She slips through the window and lingers on the sea, with no owner and no hurry.\nCelso will invent a box for that. Lúa will turn off a spotlight. Ofelia will leave a gap in the catalogue.\nAnd for the first time, you do not mistake being alone for being incomplete.')],
 [t('Juntas, no pegadas','Together, not attached'),t('El acuerdo cabe en una servilleta: puede irse; puedes echarla de menos; ninguna de las dos confundirá eso con una deuda.\nPide los domingos libres y el derecho a exagerar tus orejas al atardecer. Aceptas.\nCelso pide tres copias. Esta vez, por si alguna quiere enmarcarla.','The agreement fits on a napkin: she can leave; you can miss her; neither will mistake that for a debt.\nShe asks for Sundays off and the right to exaggerate your ears at sunset. You agree.\nCelso asks for three copies. This time, in case someone wants to frame one.')],
 [t('El recurso continúa','The appeal continues'),t('«Mía» vuelve a sonar como una cerradura. La sombra no entra.\nTres semanas después recibes una reclamación de cuarenta y seis páginas, legible solo al atardecer. Tu abogada, la planta, recomienda luz indirecta.\nPuedes volver a hablar con ella. Una mala respuesta no tiene por qué ser la última.','“Mine” sounds like a lock again. The shadow does not enter.\nThree weeks later you receive a forty-six-page claim, readable only at sunset. Your lawyer, the plant, recommends indirect light.\nYou can talk to her again. A bad answer need not be the last.')]
 ];
 const p=modal(endings[which][0],'<div class="eyebrow">'+t('La noche sí consta','The night is now on record')+'</div><p class="lede" style="white-space:pre-line"></p>');p.querySelector('p').textContent=endings[which][1];p.append(button(t('Volver al puerto','Return to the harbour'),()=>{closeModal();go('harbor',370);}),button(t('Escuchar otra vez','Listen again'),()=>{closeModal();finish();}));
}
function obj(id,label,poly,anchor,action,look,extra={}){return {id,label,poly,anchor,action,look,...extra};}
function rect(x,y,w,h){return [[x,y],[x+w,y],[x+w,y+h],[x,y+h]];}
objects.harbor=[
 obj('tavern', ['Taberna · La Última Luz','Tavern · The Last Light'],[[132,310],[171,233],[250,279],[270,426],[266,546],[140,570]],195,()=>go('tavern',375),['El único sitio donde un apagón baja la factura sin arruinar el ambiente.','The only place where a blackout lowers the bill without ruining the atmosphere.'],{exit:true,mark:[185,520]}),
 obj('plaque',['Placa de sellos','Seal plaque'],[[867,341],[895,316],[1031,316],[1061,340],[1061,530],[867,536]],979,()=>puzzles.relief(),['Cuatro impresiones prácticamente idénticas. Casi es una profesión.','Four almost identical impressions. Practically a profession.'],{mark:[962,408]}),
 obj('notices',['Tablón municipal','Municipal notices'],rect(508,310,242,139),544,()=>say('Bagheera',t('«Prohibido perder objetos no declarados. Las sombras fugadas se tramitan como iluminación defectuosa.»\nEn letra diminuta: «Toda cesión es revisable en el Archivo». Al menos hay una salida escrita.','“Undeclared objects may not be lost. Escaped shadows are processed as faulty lighting.”\nIn tiny print: “Every assignment may be reviewed at the Archive.” At least there is a way out in writing.')),['Un tablón donde incluso la chincheta necesita justificante.','A noticeboard where even the drawing pin needs a receipt.'],{mark:[642,376]}),
 obj('gate',['Cancela del archivo','Archive gate'],rect(1117,310,151,301),1145,()=>state.flags.archiveOpen?go('archive',619):note(t('Celso exige un motivo formal para dejarte pasar. El contrato podría dártelo.','Celso requires a formal reason to let you through. The contract might provide one.')),['Al otro lado está el archivo. Y más escaleras de las necesarias.','The archive is on the other side. Along with more stairs than necessary.'],{exit:true,mark:[1196,531]}),
 obj('rope',['Cabo enrollado','Coiled rope'],[[845,595],[873,539],[925,523],[981,562],[990,639],[936,663],[850,651]],914,()=>note(t('No necesito un cabo. Necesito que alguien ate los que ha dejado sueltos.','I do not need a rope. I need someone to tie up their loose ends.')),['Más ordenado que todo el sistema portuario.','Better organised than the entire port authority.'],{mark:[916,614]})
];
objects.tavern=[
 obj('harbor',['Volver a la aduana','Back to customs'],[[71,186],[139,80],[260,49],[353,112],[373,296],[341,515],[80,520]],178,()=>go('harbor',213),['Aire salado. Burocracia en suspensión.','Salt air. Suspended bureaucracy.'],{exit:true,mark:[205,466]}),
 obj('boat',['Barquito de papel','Paper boat'],[[252,363],[302,365],[323,350],[370,367],[396,399],[363,426],[309,419]],383,()=>{if(has('barco')||has('contrato'))return note(t('Ya lo llevo. Lo que queda es el recuerdo de un barco mal pagado.','I already have it. All that remains is the memory of an underpaid boat.'));add('barco');note(t('Has recogido el barquito. Tiene escritura en la cara interior.','You picked up the paper boat. There is writing on the inside.'));},['Papel doblado. No tiene matrícula; por eso aún flota.','Folded paper. It has no registration; that is why it still floats.'],{mark:[336,390]}),
 obj('projector',['Proyector de Lúa','Lúa’s projector'],[[500,239],[591,237],[674,272],[676,362],[494,361]],577,()=>{if(has('contrato'))return puzzles.contract();if(has('barco'))return give('barco','projector');note(t('Necesita algo que iluminar. El barquito del taburete parece tener letras dentro.','It needs something to illuminate. The boat on the stool seems to have writing inside.'));},['Una máquina capaz de hacer que hasta mis impuestos resulten dramáticos.','A machine capable of making even my taxes look dramatic.'],{mark:[581,297]}),
 obj('window',['Vidriera de la polilla','Moth stained glass'],[[866,95],[930,34],[1051,28],[1111,81],[1134,172],[1098,255],[1000,299],[908,268],[863,180]],1098,()=>exchange('Lúa',t('La encargué cuando todavía me gustaba que me reconocieran en todas partes. Ahora la cubro los martes.','I commissioned it when I still enjoyed being recognised everywhere. Now I cover it on Tuesdays.'),'lua'),['La polilla de la vidriera mira la luna, no el foco. Lúa eligió bien.','The moth in the glass watches the moon, not the spotlight. Lúa chose well.'],{mark:[1000,164]})
];
objects.archive=[
 obj('harbor',['Salir del archivo','Leave the archive'],rect(0,523,64,175),124,()=>go('harbor',1120),['El pasillo de vuelta a la cancela.','The passage back to the gate.'],{exit:true,mark:[35,610]}),
 obj('ledger',['Registro de tres copias','Three-copy register'],[[176,272],[418,318],[907,363],[1029,438],[685,471],[212,462]].map(([x,y])=>[x>540?x*.53:x,y]),432,()=>{remember('copies');puzzles.ledger();},['Original, archivo, recibo. Tres oportunidades para decir la misma mentira.','Original, archive, receipt. Three chances to tell the same lie.'],{mark:[339,359]}),
 obj('stairs',['Escalera del faro','Lighthouse stairs'],[[981,141],[1025,100],[1107,102],[1150,151],[1150,395],[1100,535],[981,547]],1007,()=>has('llave')?go('lighthouse',355):note(t('La puerta superior está cerrada. Ofelia tiene la llave.','The upper door is locked. Ofelia has the key.')),['Una escalera de caracol. Por una vez, sin funcionario dentro.','A spiral staircase. For once, with no official inside.'],{exit:true,mark:[1048,425]}),
 obj('prismDisplay',['Prisma del archivo','Archive prism'],[[1160,242],[1205,223],[1279,251],[1279,374],[1200,384],[1148,316]],1082,()=>has('prisma')?note(t('Ofelia ya me ha entregado el prisma testigo.','Ofelia has already given me the witness prism.')):note(t('Ofelia guarda el prisma con la llave. Antes tendrás que convencerla.','Ofelia keeps the prism with the key. You will need to convince her first.')),['Parece una gema. Es un dispositivo de declaración. Mucho menos vendible.','It looks like a gem. It is a testimony device. Much less marketable.'],{mark:[1214,307]})
];
// The ledger polygon follows the visible book, not percentages of the browser.
objects.archive.find(o=>o.id==='ledger').poly=[[177,278],[467,318],[531,436],[382,465],[197,459],[139,329]];
objects.lighthouse=[
 obj('archive',['Bajar al archivo','Down to the archive'],[[31,182],[54,96],[166,37],[245,56],[304,165],[310,328],[213,580],[17,675]],173,()=>go('archive',983),['Bajar cuesta menos que admitir un error. Aunque no tanto.','Going down takes less effort than admitting a mistake. Though not much less.'],{exit:true,mark:[88,566]}),
 obj('optics',['Matriz de espejos','Mirror array'],[[386,119],[527,69],[712,106],[835,244],[843,480],[712,613],[441,600],[353,420]],570,()=>{if(!has('prisma'))return note(t('Falta el prisma testigo. Ofelia lo conserva.','The witness prism is missing. Ofelia keeps it.'));if(!state.flags.prismInstalled){flag('prismInstalled');remember('beams');}puzzles.mirrors();},['Nueve espejos. No una combinación secreta: una red de caminos para la luz.','Nine mirrors. Not a secret combination: a network of paths for light.'],{mark:[628,327]}),
 obj('shadow',['Cápsula de la sombra','Shadow capsule'],[[1054,229],[1179,229],[1195,278],[1192,638],[1072,649],[1051,591]],982,finish,['El humo se mueve como si estuviera ensayando una respuesta.','The smoke moves as though it were rehearsing an answer.'],{mark:[1124,421]})
];
function boundsFor(name,cx,foot,visibleHeight){const s=spriteInfo[name],h=visibleHeight/s.bh*s.height,w=h*s.width/s.height;return [cx-w/2,foot-h*s.bottom,w,h];}
function npcObject(){const s=SCENES[state.scene];if(!s.npc)return null;const r=boundsFor(s.npc,s.npcX,s.foot,s.npcH),info=spriteInfo[s.npc];return obj(s.npc,[s.npc==='lua'?'Lúa':s.npc==='celso'?'Celso':'Ofelia',s.npc==='lua'?'Lúa':s.npc==='celso'?'Celso':'Ofelia'],rect(r[0]+info.left*r[2],r[1]+info.top*r[3],info.bw/info.width*r[2],info.bh/info.height*r[3]),s.npcX-160,()=>talk(s.npc),[t('Parece tener algo que decir.','They look like they have something to say.'),t('Parece tener algo que decir.','They look like they have something to say.')],{npc:true,r,mark:[s.npcX,s.foot-s.npcH*.65]});}
function inPoly(x,y,poly){let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const [xi,yi]=poly[i],[xj,yj]=poly[j];if(((yi>y)!==(yj>y))&&x<(xj-xi)*(y-yi)/(yj-yi)+xi)inside=!inside;}return inside;}
function allObjects(){const n=npcObject();return n?[n,...objects[state.scene]]:objects[state.scene];}
function hit(x,y){for(const o of allObjects().sort((a,b)=>Number(!!a.exit)-Number(!!b.exit))){if(!inPoly(x,y,o.poly))continue;if(o.npc){const s=spriteInfo[o.id],r=o.r,u=Math.floor((x-r[0])/r[2]*s.width),v=Math.floor((y-r[1])/r[3]*s.height);if(u<0||v<0||u>=s.width||v>=s.height||s.alpha[(v*s.width+u)*4+3]<55)continue;}return o;}return null;}
function action(o){if(!o)return;if(selected){const it=selected;selected=null;ui();return give(it,o.id);}if(verb==='look')return say('Bagheera',o.look[state.language==='es'?0:1]);if(verb==='talk'&&!o.npc)return note(t('No responde. Es un objeto, pero agradezco que no finja estar escuchando.','No answer. It is an object, but at least it does not pretend to listen.'));o.action();}
function request(o){if(!playing)return;hover=null;$('label').style.display='none';tx=Math.max(95,Math.min(1175,o.anchor));state.face=tx>=state.x?1:-1;if(reduced||Math.abs(tx-state.x)<12){state.x=tx;action(o);}else pending=()=>action(o);}
function go(scene,x){closeModal();closeDialogue();pending=null;state.scene=scene;state.x=tx=x;state.face=x>700?-1:1;selected=null;hover=null;state.lamp.x=x;state.lamp.y=330;state.lamp.pinned=false;state.visited[scene]=true;ui();save();note(SCENES[scene].title[state.language==='es'?0:1],2000);}
function ui(){document.documentElement.lang=state.language;document.title=t('BRUMA — La noche no consta','BRUMA — The night is not on record');$('location').textContent=SCENES[state.scene].title[state.language==='es'?0:1];$('journal').textContent=t('Cuaderno','Notebook');$('settings').textContent=t('Ajustes','Settings');$('lang').textContent=state.language==='es'?'EN':'ES';$('zones').title=t('Mostrar zonas · H','Show hotspots · H');$('zones').classList.toggle('active',showZones);$('verbs').replaceChildren();for(const [id,es,en] of [['interact','Interactuar','Interact'],['look','Examinar','Examine'],['talk','Hablar','Talk']])$('verbs').append(button(t(es,en),()=>{verb=id;selected=null;ui();},verb===id?'active':''));$('inventory').replaceChildren();for(const item of state.inventory){const data=items[item];if(!data)continue;const b=button('',()=>{selected=selected===item?null:item;ui();if(selected)note(data.desc[state.language==='es'?0:1],3500);},selected===item?'active':'');b.innerHTML='<span class="item-icon">'+data.icon+'</span><span>'+data.name[state.language==='es'?0:1]+'</span>';b.title=data.desc[state.language==='es'?0:1];b.dataset.item=item;b.oncontextmenu=e=>{e.preventDefault();say('Bagheera',data.desc[state.language==='es'?0:1]);};$('inventory').append(b);}if(!state.inventory.length)for(let i=0;i<4;i++){const span=document.createElement('span');span.className='empty-pocket';$('inventory').append(span);}const current=state.flags.beams?t('Escuchar a mi sombra.','Listen to my shadow.'):has('llave')?t('Hacer declarar al faro.','Make the lighthouse testify.'):state.flags.archiveOpen?t('Comparar las tres copias.','Compare the three copies.'):has('contrato')?t('Exigir una revisión a Celso.','Request a review from Celso.'):has('filtro')?t('Leer las dos tintas del contrato.','Read the contract’s two inks.'):has('calco')?t('Llevar el calco a Lúa.','Take the rubbing to Lúa.'):t('Averiguar adónde se fue mi sombra.','Find out where my shadow went.');$('objective').textContent=current;$('pocket-label').textContent=t('BOLSILLOS','POCKETS');$('pin').classList.toggle('active',state.lamp.pinned);$('pin').querySelector('span').textContent=state.lamp.pinned?t('Luz fija','Pinned light'):t('Luz libre','Free light');$('spectrum').querySelector('span').textContent=t(['Blanca','Ámbar','Cian'][state.lamp.color],['White','Amber','Cyan'][state.lamp.color]);$('normals').classList.toggle('active',renderer?.normalView);$('help-line').textContent=selected?t('Usar '+items[selected].name[0]+' con… · Esc para soltar','Use '+items[selected].name[1]+' with… · Esc to cancel'):t('Clic para andar o interactuar · Clic derecho: examinar · L: fijar luz · H: zonas · N: normales','Click to walk or interact · Right-click: examine · L: pin light · H: hotspots · N: normals');drawMarkers();}
function drawMarkers(){const list=allObjects().filter(o=>showZones||o.exit);$('markers').innerHTML=list.map(o=>{const [x,y]=o.mark||[o.anchor,550];const label=o.label[state.language==='es'?0:1];return (showZones?'<polygon points="'+o.poly.map(p=>p.join(',')).join(' ')+'" fill="#ffe4a208" stroke="#e4c68988" stroke-width="1.5" stroke-dasharray="5 4"/>':'')+'<g transform="translate('+x+','+y+')"><circle class="marker" r="13"/><text text-anchor="middle" y="5">'+(o.exit?'↗':'·')+'</text>'+(showZones?'<text text-anchor="middle" y="-22">'+label+'</text>':'')+'</g>';}).join('');}
function journal(){const p=modal(t('El cuaderno','The notebook'),'<div class="clue">'+t('Nada se anota antes de descubrirlo. Las pistas son opcionales y progresivas.','Nothing is recorded before you discover it. Hints are optional and progressive.')+'</div>');$('panel-title').textContent=t('Cuaderno de una gata sin sombra','Notes of a shadowless cat');for(const id of state.notes){const n=notes[id];if(!n)continue;const d=document.createElement('div');d.className='journal-entry';const b=document.createElement('b');b.textContent=n[state.language==='es'?0:1];const q=document.createElement('p');q.textContent=n[state.language==='es'?2:3];d.append(b,q);p.append(d);}p.append(button(t('Necesito una pista','I need a hint'),hint,'section-rule'));}
function hint(){const stage=!has('calco')?'seal':!has('filtro')?'filter':!has('contrato')?'contract':!state.flags.archiveOpen?'gate':!has('prueba')?'proof':!has('llave')?'key':!state.flags.beams?'beams':'end';const list={
 seal:[['Habla con Celso sobre tu sombra. La caída de su sello importa.','Ask Celso about your shadow. His dropped seal matters.'],['Abre la placa metálica y baja la altura de la luz. Observa dónde se interrumpe el anillo de cada sello.','Open the metal plaque and lower the light. Look for the break in each seal’s ring.'],['La muesca está a las seis: el sello B.','The nick is at six o’clock: seal B.']],
 filter:[['Lúa trabaja con la luz. Está en la taberna del arco izquierdo.','Lúa works with light. She is in the tavern through the left arch.'],['Selecciona el calco en el inventario y dáselo a Lúa.','Select the rubbing in your inventory and give it to Lúa.']],
 contract:[['El papel puede esconder texto también al doblarse.','Folded paper can hide writing too.'],['Recoge el barco del taburete y úsalo con el proyector.','Take the boat from the stool and use it on the projector.'],['Alterna ámbar y cian en el examen del contrato y lee ambas capas.','Switch between amber and cyan while examining the contract and read both layers.']],
 gate:[['El derecho de revisión no es un favor.','The right of review is not a favour.'],['Presenta el contrato a Celso. Después entra por la cancela de la derecha.','Show the contract to Celso, then enter the gate on the right.']],
 proof:[['Ofelia conoce la progresión que deja un único trazo.','Ofelia knows the progression left by a single stroke.'],['En el registro, usa luz baja. Compara los surcos de A, B y C.','In the register, use low light. Compare the grooves in A, B and C.'],['Las profundidades son 3, 3 y 1. La copia B recibió otra escritura.','The depths are 3, 3 and 1. Copy B was written on again.']],
 key:[['Una prueba no sirve si no se la enseñas a quien tiene algo que explicar.','Evidence is not useful until you show it to someone with explaining to do.'],['Presenta la prueba a Ofelia y termina la conversación.','Show the evidence to Ofelia and finish the conversation.']],
 beams:[['Los receptores están etiquetados. Cada espejo cambia la dirección del haz.','Receivers are labelled. Every mirror changes a beam’s direction.'],['Resuelve primero el rojo: debe volver al lateral izquierdo, una fila más abajo.','Start with red: it must return to the left edge, one row down.'],['Una solución, por filas: \\ \\ \\ / \\ \\ / \\ /. También se aceptan otros recorridos válidos.','One solution, by rows: \\ \\ \\ / \\ \\ / \\ /. Other valid routes are accepted too.']],
 end:[['La luz ha hecho su trabajo. Ahora escucha.','Light has done its job. Now listen.']]
 }[stage];const n=state.hints[stage]||0;state.hints[stage]=Math.min(n+1,list.length);save();const p=modal(t('Una pista, no una orden','A hint, not an order'),'<p class="lede"></p>');p.querySelector('p').textContent=list[Math.min(n,list.length-1)][state.language==='es'?0:1];if(n<list.length-1)p.append(button(t('Más explícita','More explicit'),hint));}
function settings(){const p=modal(t('Ajustes','Settings'),'<div class="setting"><span>'+t('Exposición de la escena','Scene exposure')+'</span><input id="exposure" type="range" min="1" max="2.8" step="0.05" value="'+state.exposure+'"></div><p class="small">'+t('Los mapas son relieves aproximados. N alterna el resultado iluminado y los vectores normales. El arte original aún mezcla acabados; esta revisión no lo convierte en un nuevo set dibujado a mano.','The maps are approximate reliefs. N switches between the lit result and the normal vectors. The original art still mixes finishes; this revision does not turn it into a newly hand-drawn set.')+'</p><div class="row" id="settings-buttons"></div><p class="technical" id="technical"></p>');$('exposure').oninput=e=>{state.exposure=+e.target.value;save();};$('settings-buttons').append(button(t('Alternar normales','Toggle normal maps'),()=>{renderer.normalView=!renderer.normalView;ui();}),button(t('Controles','Controls'),controls),button(t('Nueva partida…','New game…'),resetPrompt));$('technical').textContent='BRUMA '+VERSION+' · WebGL\n'+t('Mundo: 1280 × 720 · Proporción fija\nGuardado local en este navegador · Sin cuentas ni analítica','World: 1280 × 720 · Fixed aspect ratio\nLocal save in this browser · No accounts or analytics');}
function controls(){modal(t('Cómo moverse por la noche','How to get around at night'),'<p>'+t('Pulsa el suelo para caminar. Interactuar elige la acción del objeto: hablar, recoger, examinar un mecanismo o atravesar una salida. Examinar nunca recoge ni cambia de sala.','Click the floor to walk. Interact chooses an object’s action: talk, pick up, examine a mechanism or go through an exit. Examine never picks things up or changes rooms.')+'</p><p>'+t('Selecciona un objeto del inventario y luego su destino. Esc lo suelta. El clic derecho examina. H muestra las zonas usando la misma geometría que comprueba los clics.','Select an inventory item, then its target. Esc releases it. Right-click examines. H shows hotspots using the same geometry that tests clicks.')+'</p><p>'+t('La luz sigue al puntero. L la fija donde está, para poder pulsar otra cosa sin moverla. El filtro permite cambiar el color. N muestra los mapas de normales.','Light follows the pointer. L pins it, so you can click elsewhere without moving it. The filter changes its colour. N shows normal maps.')+'</p><p>'+t('F recorre los objetos, Enter interactúa con el seleccionado; flechas para andar; 1–3 cambian verbo. Los paneles y conversaciones conservan el foco del teclado.','F cycles through objects, Enter interacts with the selected one; arrows walk; 1–3 change verbs. Panels and conversations retain keyboard focus.')+'</p>');}
function resetPrompt(){const p=modal(t('¿Empezar de nuevo?','Start again?'),'<p>'+t('Se borrará el progreso de esta versión en este navegador.','Progress for this version in this browser will be erased.')+'</p>');p.append(button(t('Conservar partida','Keep my game'),closeModal),button(t('Empezar de nuevo','Start again'),()=>{const lang=state.language;state=initial();state.language=lang;tx=state.x;playing=true;ui();closeModal();save();},'primary'));}
function intro(){const p=modal('BRUMA','<img class="intro-art" src="assets/cat-look.webp" alt="Bagheera"><div class="eyebrow">'+t('La noche no consta','The night is not on record')+'</div><p class="lede">'+t('Tu sombra se ha ido. El puerto asegura que eso no es posible sin rellenar un formulario.','Your shadow has left. The port insists that is impossible without filling in a form.')+'</p><p>'+t('Averigua qué firmó, quién cambió la letra pequeña y por qué nadie parece dispuesto a apagar el faro.','Find out what she signed, who changed the small print, and why nobody seems prepared to turn off the lighthouse.')+'</p><p class="small">'+t('Point & click · Puzles de observación y luz · Guardado automático local','Point & click · Observation and light puzzles · Local autosave')+'</p><div class="intro-foot" id="intro-buttons"></div>');$('intro-buttons').append(button(stored?t('Continuar','Continue'):t('Entrar en la noche','Enter the night'),()=>{closeModal();playing=true;ui();save();if(!stored)note(t('Bagheera: «Me habría conformado con perder las llaves».','Bagheera: “I would have settled for losing my keys.”'));},'primary'),button(t('Controles','Controls'),controls));if(stored)$('intro-buttons').append(button(t('Nueva partida','New game'),resetPrompt));}
function position(e){const r=$('scene').getBoundingClientRect();return {x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height};}
function resize(){const r=$('stage').getBoundingClientRect(),scale=Math.min(r.width/W,r.height/H);const w=W*scale,h=H*scale;Object.assign($('scene').style,{width:w+'px',height:h+'px',left:(r.width-w)/2+'px',top:(r.height-h)/2+'px'});}
function markHover(o,x,y){hover=o;$('world').style.cursor=o?'pointer':'default';if(o){$('label').textContent=(selected?t('Usar ','Use ')+items[selected].name[state.language==='es'?0:1]+t(' con ',' on '):verb==='look'?t('Examinar ','Examine '):'')+o.label[state.language==='es'?0:1];$('label').style.display='block';$('label').style.left=Math.max(100,Math.min(W-100,x))/W*100+'%';$('label').style.top=Math.max(55,y-20)/H*100+'%';}else $('label').style.display='none';}
function spectrum(){if(!has('filtro'))return note(t('Aún no tengo un filtro. La luz blanca es la única que traía de serie.','I do not have a filter yet. White light is all that came as standard.'));state.lamp.color=(state.lamp.color+1)%3;ui();save();}
function wire(){
 $('world').addEventListener('pointermove',e=>{if(!playing||!$('overlay').hidden||!$('dialogue').hidden)return;const p=position(e);if(!state.lamp.pinned){state.lamp.x=p.x;state.lamp.y=p.y;}markHover(hit(p.x,p.y),p.x,p.y);});
 $('world').addEventListener('pointerleave',()=>markHover(null,0,0));
 $('world').addEventListener('click',e=>{if(!playing||!$('overlay').hidden||!$('dialogue').hidden)return;const p=position(e);const o=hit(p.x,p.y);if(o)return request(o);if(selected){selected=null;ui();return;}if(p.y>535){pending=null;tx=Math.max(105,Math.min(1175,p.x));state.face=tx>=state.x?1:-1;$('world').focus();}});
 $('world').tabIndex=0;
 $('world').addEventListener('contextmenu',e=>{e.preventDefault();if(!playing||!$('overlay').hidden)return;const p=position(e),o=hit(p.x,p.y);if(o)say('Bagheera',o.look[state.language==='es'?0:1]);});
 $('dialogue-close').onclick=closeDialogue;$('overlay').addEventListener('click',e=>{if(e.target===$('overlay'))closeModal();});
 $('journal').onclick=journal;$('settings').onclick=settings;$('zones').onclick=()=>{showZones=!showZones;ui();};$('pin').onclick=()=>{state.lamp.pinned=!state.lamp.pinned;ui();save();};$('spectrum').onclick=spectrum;$('normals').onclick=()=>{renderer.normalView=!renderer.normalView;ui();};$('lang').onclick=()=>{state.language=state.language==='es'?'en':'es';closeDialogue();closeModal();ui();save();if(!playing)intro();};
 let keyboardIndex=-1;
 document.addEventListener('keydown',e=>{
  if(e.key==='Escape'){if(!$('overlay').hidden)closeModal();else if(!$('dialogue').hidden)closeDialogue();else{selected=null;pending=null;tx=state.x;ui();}return;}
  if(e.key==='Tab'&&(!$('overlay').hidden||!$('dialogue').hidden)){const parent=!$('overlay').hidden?$('panel'):$('dialogue'),buttons=[...parent.querySelectorAll('button,input')].filter(el=>!el.disabled);const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}return;}
  if(!playing||!$('overlay').hidden||!$('dialogue').hidden||e.target.tagName==='INPUT')return;
  const k=e.key.toLowerCase();if(k==='l')$('pin').click();if(k==='n')$('normals').click();if(k==='h')$('zones').click();if(k==='j')journal();if(['1','2','3'].includes(k)){verb=['interact','look','talk'][+k-1];selected=null;ui();}
  if(k==='f'){e.preventDefault();keyboardIndex=(keyboardIndex+1)%allObjects().length;const o=allObjects()[keyboardIndex];markHover(o,...(o.mark||[o.anchor,550]));}
  if(k==='enter'&&hover&&e.target.tagName!=='BUTTON'){e.preventDefault();request(hover);}
  if(k==='arrowleft'||k==='arrowright'){e.preventDefault();pending=null;tx=Math.max(105,Math.min(1175,state.x+(k==='arrowleft'?-90:90)));state.face=k==='arrowleft'?-1:1;}
 });new ResizeObserver(resize).observe($('stage'));resize();
 document.addEventListener('visibilitychange',()=>{if(document.hidden)save();});window.addEventListener('pagehide',save);document.addEventListener('bruma-render-error',()=>modal(t('Se ha interrumpido el render','Rendering interrupted'),'<p>'+t('El navegador ha perdido el contexto gráfico. Tu progreso está guardado. Recarga la página para recuperar la imagen.','The browser lost its graphics context. Your progress is saved. Reload the page to recover the image.')+'</p>'));
}
function frame(now){
 requestAnimationFrame(frame);if(!renderer||renderer.lost||document.hidden)return;const dt=Math.min(.2,(now-lastTime)/1000||.016);lastTime=now;
 const delta=tx-state.x;moving=playing&&Math.abs(delta)>1.5&&$('overlay').hidden&&$('dialogue').hidden;
 if(moving){const step=Math.sign(delta)*Math.min(Math.abs(delta),205*dt);state.x+=step;state.face=step>=0?1:-1;walkPhase+=Math.abs(step)/42*Math.PI*2;}else if(Math.abs(delta)<=1.5){state.x=tx;if(pending){const action=pending;pending=null;action();save();}}
 const scene=SCENES[state.scene],lamp=state.lamp,colors=[[2.75,2.55,2.1],[3.6,1.45,.2],[.25,2.55,3.65]],lights=[...scene.lights.map(l=>({...l,p:[...l.p],c:[...l.c]})),{p:[lamp.x,lamp.y,lamp.z],c:colors[lamp.color],r:820}];
 if(!reduced)lights[0].c=lights[0].c.map(c=>c*(1+.023*Math.sin(now*.0031)+.015*Math.sin(now*.0074)));
 if(state.scene==='lighthouse'&&state.flags.beams){lights[0].c=[2.3,.4,.3];lights[1].c=[.25,1.4,3.2];lights[2].c=[.5,2.2,1.1];}
 renderer.begin(lights,scene.ambient,state.exposure);renderer.draw(state.scene,[0,0,W,H],{spec:.18});
 const npc=npcObject();if(npc){renderer.draw('contact',[scene.npcX-65,scene.foot-9,130,19],{shadow:true,opacity:.65});renderer.draw(npc.id,npc.r,{spec:.045,gain:.54});}
 const r=boundsFor(cat.name,state.x,cat.foot,cat.height);const phase=reduced?0:moving?walkPhase:now*.001;
 renderer.draw('contact',[state.x-62,cat.foot-8,124,15],{shadow:true,opacity:.4});
 renderer.draw(cat.name,r,{cat:true,flip:state.face,phase,walk:moving?1:0,spec:.02,gain:.40});renderer.end();
 effects(now,lights);modalTick?.(now);
}
function effects(now,lights){const c=$('effects').getContext('2d');c.clearRect(0,0,W,H);if(renderer.normalView)return;
 // Subtle atmosphere is a separate overlay; material relighting is in WebGL.
 if(!reduced){c.globalCompositeOperation='screen';for(let i=0;i<32;i++){const x=(i*179+Math.sin(now*.00023+i)*15)%W,y=100+(i*67+now*.008)%470;const light=lights[3],dist=Math.hypot(x-light.p[0],y-light.p[1]),alpha=Math.max(0,1-dist/440)*.35;c.fillStyle='rgba(236,211,166,'+alpha+')';c.beginPath();c.arc(x,y,.7+(i%3)*.35,0,Math.PI*2);c.fill();}c.globalCompositeOperation='source-over';}
 if(state.lamp.pinned){c.strokeStyle='#e6cc9699';c.lineWidth=1;c.beginPath();c.arc(state.lamp.x,state.lamp.y,9,0,Math.PI*2);c.moveTo(state.lamp.x-13,state.lamp.y);c.lineTo(state.lamp.x+13,state.lamp.y);c.moveTo(state.lamp.x,state.lamp.y-13);c.lineTo(state.lamp.x,state.lamp.y+13);c.stroke();}
}
const game={t,$,get state(){return state;},has,add,remove,flag,remember,note,save,modal,closeModal,say,button,ui,go,finish,setTick(fn){modalTick=fn;},get renderer(){return renderer;}};
async function boot(){try{
 renderer=new Renderer($('world'));await renderer.load(['harbor','tavern','archive','lighthouse','cat-look','cat-idle','cat-walk','cat-sit','celso','lua','ofelia'],v=>$('progress').value=v);
 for(const [name,im] of Object.entries(renderer.images)){if(SCENES[name])continue;const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(im,0,0);const data=ctx.getImageData(0,0,c.width,c.height).data;let x0=im.width,y0=im.height,x1=0,y1=0;for(let y=0;y<im.height;y++)for(let x=0;x<im.width;x++)if(data[(y*im.width+x)*4+3]>40){x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y);}spriteInfo[name]={width:im.width,height:im.height,bw:x1-x0+1,bh:y1-y0+1,left:x0/im.width,top:y0/im.height,bottom:(y1+1)/im.height,alpha:data};}
 const shadow=document.createElement('canvas');shadow.width=128;shadow.height=40;const shade=shadow.getContext('2d'),gradient=shade.createRadialGradient(64,20,2,64,20,60);gradient.addColorStop(0,'#00000077');gradient.addColorStop(1,'#00000000');shade.fillStyle=gradient;shade.fillRect(0,0,128,40);const flat=document.createElement('canvas');flat.width=flat.height=2;const flatctx=flat.getContext('2d');flatctx.fillStyle='rgb(128,128,255)';flatctx.fillRect(0,0,2,2);renderer.add('contact',shadow,flat);
 puzzles=initPuzzles(game);wire();ui();$('loading').hidden=true;playing=true;requestAnimationFrame(frame);intro();
 // Read-only diagnostics used by the browser regression suite, not progression cheats.
 window.Bruma=Object.freeze({version:VERSION,get state(){return JSON.parse(JSON.stringify(state));},get moving(){return moving;},get busy(){return pending!==null||Math.abs(tx-state.x)>1.5;},get ready(){return true;},objects:()=>allObjects().map(({id,poly,mark,r})=>({id,poly,mark,r})),hit:(x,y)=>hit(x,y)?.id||null,worldToClient:(x,y)=>{const r=$('scene').getBoundingClientRect();return {x:r.left+x/W*r.width,y:r.top+y/H*r.height};},get rendererError(){return renderer.gl.getError();},get normalView(){return renderer.normalView;}});
 }catch(e){console.error(e);$('load-status').textContent=t('No se ha podido iniciar: ','Could not start: ')+e.message;$('loading').append(button(t('Reintentar','Retry'),()=>location.reload()));}}
boot();
