#!/usr/bin/env python3
"""Reproduce or extend POTAMORSE's seeded inspiration pipeline.

The design used two layers of randomness:

1. MediaWiki's ``list=random`` supplied an uncontrolled article pool.
2. A cryptographic seed was frozen, then Python's deterministic PRNG selected
   eight items. A SHA-256 selector chose a second-hop link for each article.

The exact 2026-09-03 pool is in research_snapshot.json.  Run without ``--live``
to reproduce the selection exactly.  ``--live`` performs a new MediaWiki pull;
results can change because Wikipedia changes.

Examples
--------
    python3 research_seed.py
    python3 research_seed.py --live --new-seed --count 20
    python3 research_seed.py --seed 6ba910032e277de76e2a491e5f450166 --markdown
"""
from __future__ import annotations

import argparse
import hashlib
import itertools
import json
import random
import secrets
import urllib.parse
import urllib.request
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Iterable

HERE = Path(__file__).resolve().parent
SNAPSHOT_PATH = HERE / "research_snapshot.json"
DEFAULT_SEED = "6ba910032e277de76e2a491e5f450166"
WIKIPEDIA_API = "https://en.wikipedia.org/w/api.php"
USER_AGENT = "PotamorseDesignAudit/1.0 (LagartijaLabs; noncommercial research)"


@dataclass(frozen=True)
class Candidate:
    geometry: str
    interaction: str
    objective: str
    rhythm: str
    board: str
    score: float


def fetch_json(parameters: dict[str, str | int]) -> dict:
    query = urllib.parse.urlencode({"format": "json", "formatversion": 2, **parameters})
    request = urllib.request.Request(f"{WIKIPEDIA_API}?{query}", headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=20) as response:  # noqa: S310 — intentional public API
        return json.load(response)


def random_articles(count: int) -> list[str]:
    data = fetch_json({"action": "query", "list": "random", "rnnamespace": 0, "rnlimit": count})
    return [entry["title"] for entry in data["query"]["random"]]


def article_links(title: str, limit: int = 500) -> list[str]:
    links: list[str] = []
    continuation: dict[str, str | int] = {}
    while len(links) < limit:
        data = fetch_json({
            "action": "query",
            "prop": "links",
            "titles": title,
            "plnamespace": 0,
            "pllimit": "max",
            **continuation,
        })
        page = data["query"]["pages"][0]
        links.extend(link["title"] for link in page.get("links", []))
        if "continue" not in data:
            break
        continuation = data["continue"]
    return links[:limit]


def seeded_sample(pool: list[str], seed_hex: str, count: int = 8) -> tuple[list[int], list[str]]:
    rng = random.Random(int(seed_hex, 16))
    indices = rng.sample(range(len(pool)), min(count, len(pool)))
    return indices, [pool[index] for index in indices]


def second_hop(title: str, links: list[str], seed_hex: str) -> str | None:
    if not links:
        return None
    digest = hashlib.sha256(f"{seed_hex}|{title}|stage2".encode()).digest()
    index = int.from_bytes(digest, "big") % len(links)
    return links[index]


def frozen_pool(snapshot: dict) -> list[str]:
    return [title for batch in snapshot["random_source"]["batches"] for title in batch]


def mechanical_candidates(seed_hex: str) -> list[Candidate]:
    """Evaluate the complete morphology generated by the retained sources.

    The random stage selected the source material.  This stage is deliberately
    exhaustive: every geometry × interaction × objective × rhythm × board
    combination is scored from declared priors.  The seed only shuffles equal-
    scoring candidates before Python's stable sort, making tie-breaking
    reproducible without silently excluding a potentially better design.

    Scores rank prototypes for testing; they are not measurements of fun.
    """
    # Tuple order: clarity, depth, symmetry, source cohesion, complexity cost.
    geometries = {
        "dual_slider": (2.9, 3.0, 2.8, 3.0, -1.2),
        "current_step": (2.7, 1.8, 2.8, 2.5, -.5),
        "colored_paths": (1.9, 2.7, 2.5, 1.8, -1.6),
    }
    interactions = {
        "line_of_sight_pin": (2.5, 3.0, 3.0, 2.8, -1.0),
        "adjacent_bracket": (2.8, 1.9, 3.0, 2.4, -.7),
        "displacement_capture": (2.6, 2.5, 2.8, 1.2, -.8),
    }
    objectives = {
        "fixed_bank_distance": (2.8, 2.9, 3.0, 3.0, -.8),
        "first_three_refuges": (3.0, 2.3, 2.4, 2.9, -.6),
        "connect_the_banks": (2.1, 2.6, 2.6, 1.7, -1.2),
    }
    rhythms = {
        "thue_morse": (2.3, 3.0, 3.0, 3.0, -1.0),
        "strict_alternation": (3.0, 2.0, 2.6, 1.4, -.2),
        "random_tide": (2.5, 1.8, 2.1, 2.7, -.7),
    }
    boards = {
        "5x5": (3.0, 2.5, 3.0, 2.7, -.3),
        "6x6": (2.4, 2.9, 3.0, 2.5, -.7),
    }

    dimensions = [geometries, interactions, objectives, rhythms, boards]
    all_keys = list(itertools.product(*(dimension.keys() for dimension in dimensions)))
    # Stable seeded shuffle = deterministic tie-breaker, not candidate sampling.
    rng = random.Random(int(seed_hex, 16) ^ 0x504F54414D4F5253)
    rng.shuffle(all_keys)
    candidates: list[Candidate] = []

    for keys in all_keys:
        vectors = [dimension[key] for dimension, key in zip(dimensions, keys)]
        clarity = sum(v[0] for v in vectors)
        depth = sum(v[1] for v in vectors)
        symmetry = sum(v[2] for v in vectors)
        cohesion = sum(v[3] for v in vectors)
        complexity = sum(v[4] for v in vectors)

        # Interaction terms are declared here rather than discovered after the
        # fact.  They encode whether two inspirations reinforce one another.
        synergy = 0.0
        if keys[0] == "dual_slider" and keys[3] == "thue_morse":
            synergy += 2.0  # two geometries gain meaning from a visible phrase
        if keys[1] == "line_of_sight_pin" and keys[2] == "fixed_bank_distance":
            synergy += 1.4  # reversible tempo pressure, not elimination
        if keys[2] == "fixed_bank_distance" and keys[4] == "5x5":
            synergy += .8   # interaction arrives before the short season ends
        if keys[0] == "dual_slider" and keys[1] == "line_of_sight_pin":
            synergy += .8   # each geometry creates distinct pressure lines
        if keys[0] == "dual_slider" and keys[2] == "fixed_bank_distance":
            synergy += .6
        if keys[3] == "thue_morse" and keys[4] == "5x5":
            synergy += .5   # all 16 pulses remain readable at one glance
        if keys[1] == "displacement_capture":
            synergy -= 1.4  # contradicted the nonviolent ecological synthesis
        if keys[3] == "random_tide":
            synergy -= .9   # undermined perfect-information deduction
        if keys[3] == "strict_alternation":
            synergy -= .25  # fair, but mechanically generic and predictable

        total = .23 * clarity + .25 * depth + .20 * symmetry + .22 * cohesion + complexity + synergy
        candidates.append(Candidate(*keys, round(total, 3)))

    return sorted(candidates, key=lambda candidate: candidate.score, reverse=True)

def markdown_report(seed: str, pool: list[str], indices: list[int], sample: list[str], hops: dict[str, str | None], candidates: list[Candidate]) -> str:
    lines = [
        "# Seeded research run",
        "",
        f"- Seed: `{seed}`",
        f"- Pool size: {len(pool)}",
        f"- Selected indices: `{indices}`",
        "",
        "## Selected articles and second hops",
        "",
    ]
    for title in sample:
        lines.append(f"- **{title}** → {hops.get(title) or 'no eligible link'}")
    lines.extend(["", "## Highest-ranked combinations from the exhaustive morphology", ""])
    for rank, candidate in enumerate(candidates[:8], 1):
        lines.append(
            f"{rank}. `{candidate.geometry}` · `{candidate.interaction}` · "
            f"`{candidate.objective}` · `{candidate.rhythm}` · `{candidate.board}` — **{candidate.score:.3f}**"
        )
    lines.extend([
        "",
        "> The random articles determine the design vocabulary; the full 3×3×3×3×2 morphology (162 candidates) is then ranked without sampling. The fixed-distance objective and two-leg swap were retained after race variants failed the tests recorded in research_snapshot.json.",
    ])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--seed", default=DEFAULT_SEED, help="hex seed")
    parser.add_argument("--new-seed", action="store_true", help="generate a cryptographic 128-bit seed")
    parser.add_argument("--live", action="store_true", help="pull a fresh random Wikipedia pool and live second-hop links")
    parser.add_argument("--count", type=int, default=20, help="pool size for --live (default: 20)")
    parser.add_argument("--sample", type=int, default=8, help="number selected from the pool (default: 8)")
    parser.add_argument("--markdown", action="store_true", help="write markdown instead of JSON")
    parser.add_argument("--output", type=Path, help="optional output path")
    args = parser.parse_args()

    seed = secrets.token_hex(16) if args.new_seed else args.seed.lower().removeprefix("0x")
    int(seed, 16)  # validate
    snapshot = json.loads(SNAPSHOT_PATH.read_text(encoding="utf-8"))
    pool = random_articles(args.count) if args.live else frozen_pool(snapshot)
    indices, sample = seeded_sample(pool, seed, args.sample)

    hops: dict[str, str | None] = {}
    if args.live:
        for title in sample:
            try:
                hops[title] = second_hop(title, article_links(title), seed)
            except Exception as exc:  # network audit should preserve partial results
                hops[title] = f"ERROR: {exc}"
    elif seed == snapshot["seed_hex"] and sample == snapshot["seeded_sample"]:
        hops = {entry["from"]: entry["to"] for entry in snapshot["second_hops"]}
    else:
        hops = {title: None for title in sample}

    candidates = mechanical_candidates(seed)
    if args.markdown:
        output = markdown_report(seed, pool, indices, sample, hops, candidates)
    else:
        output = json.dumps({
            "seed": seed,
            "pool": pool,
            "selected_indices": indices,
            "selected": sample,
            "second_hops": hops,
            "mechanical_candidate_count": len(candidates),
            "mechanical_candidates": [asdict(candidate) for candidate in candidates],
            "warning": "The exhaustive score prioritizes prototypes; it is not a measurement of fun.",
        }, indent=2, ensure_ascii=False)

    if args.output:
        args.output.write_text(output + "\n", encoding="utf-8")
        print(args.output)
    else:
        print(output)


if __name__ == "__main__":
    main()