(()=>{"use strict";
const N=8,DIRS=[[-1,-1],[-1,1],[1,-1],[1,1]],LEVELS={calma:{label:"Calma",depth:2,noise:.32},taller:{label:"Taller",depth:4,noise:.06},maestra:{label:"Maestra",depth:6,noise:0}};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],opp=p=>p==="white"?"black":"white",inside=(r,c)=>r>=0&&r<N&&c>=0&&c<N,playable=(r,c)=>(r+c)%2===0,clone=b=>b.map(row=>row.map(p=>p?{...p}:null));
const boardEl=$("#board"),moveList=$("#moveList"),statusPanel=$("#statusPanel"),statusTitle=$("#statusTitle"),statusDetail=$("#statusDetail"),statusLabel=$("#statusLabel"),undoButton=$("#undoButton"),soundSwitch=$("#soundSwitch"),gameOverDialog=$("#gameOverDialog");
let audioCtx=null;
function initialBoard(){const b=Array.from({length:N},()=>Array(N).fill(null));for(let r=0;r<3;r++)for(let c=0;c<N;c++)if(playable(r,c))b[r][c]={player:"black",king:false};for(let r=5;r<N;r++)for(let c=0;c<N;c++)if(playable(r,c))b[r][c]={player:"white",king:false};return b}
function fresh(human="white",difficulty="taller"){return{board:initialBoard(),human,ai:opp(human),turn:"white",difficulty,sound:true,selected:null,prefix:[],candidates:[],history:[],moves:[],result:null,thinking:false,halfmove:0,reps:{},stats:null}}
let state=fresh();
function captureSeqs(board,r,c,piece){const out=[];function walkMan(b,cr,cc,path,caps,kings){let any=false;const dirs=piece.player==="white"?[[-1,-1],[-1,1]]:[[1,-1],[1,1]];for(const[dR,dC]of dirs){const mr=cr+dR,mc=cc+dC,tr=cr+2*dR,tc=cc+2*dC;if(!inside(tr,tc)||!b[mr]?.[mc]||b[mr][mc].player===piece.player||b[tr][tc])continue;any=true;const nb=clone(b),taken=nb[mr][mc];nb[cr][cc]=null;nb[mr][mc]=null;nb[tr][tc]=piece;walkMan(nb,tr,tc,[...path,{r:tr,c:tc}],[...caps,{r:mr,c:mc}],kings+(taken.king?1:0))}if(!any&&caps.length)out.push({from:path[0],to:path[path.length-1],path,captures:caps,capturedKings:kings,capture:true})}
function walkKing(b,cr,cc,path,caps,kings){let any=false;for(const[dR,dC]of DIRS){let rr=cr+dR,cc2=cc+dC,enemy=null;while(inside(rr,cc2)){const q=b[rr][cc2];if(!enemy){if(!q){rr+=dR;cc2+=dC;continue}if(q.player===piece.player)break;enemy={r:rr,c:cc2,p:q};rr+=dR;cc2+=dC;continue}else{if(q)break;any=true;const nb=clone(b);nb[cr][cc]=null;nb[enemy.r][enemy.c]=null;nb[rr][cc2]=piece;walkKing(nb,rr,cc2,[...path,{r:rr,c:cc2}],[...caps,{r:enemy.r,c:enemy.c}],kings+(enemy.p.king?1:0));rr+=dR;cc2+=dC}}}if(!any&&caps.length)out.push({from:path[0],to:path[path.length-1],path,captures:caps,capturedKings:kings,capture:true})}
const start={r,c};piece.king?walkKing(clone(board),r,c,[start],[],0):walkMan(clone(board),r,c,[start],[],0);return out}
function legalMoves(board,player){let caps=[];for(let r=0;r<N;r++)for(let c=0;c<N;c++){const p=board[r][c];if(p?.player===player)caps.push(...captureSeqs(board,r,c,p))}if(caps.length){const max=Math.max(...caps.map(m=>m.captures.length));caps=caps.filter(m=>m.captures.length===max);const q=Math.max(...caps.map(m=>m.capturedKings));return caps.filter(m=>m.capturedKings===q)}const out=[];for(let r=0;r<N;r++)for(let c=0;c<N;c++){const p=board[r][c];if(p?.player!==player)continue;if(p.king){for(const[dR,dC]of DIRS){let rr=r+dR,cc=c+dC;while(inside(rr,cc)&&!board[rr][cc]){out.push({from:{r,c},to:{r:rr,c:cc},path:[{r,c},{r:rr,c:cc}],captures:[],capturedKings:0,capture:false});rr+=dR;cc+=dC}}}else{const dr=player==="white"?-1:1;for(const dc of[-1,1]){const rr=r+dr,cc=c+dc;if(inside(rr,cc)&&!board[rr][cc])out.push({from:{r,c},to:{r:rr,c:cc},path:[{r,c},{r:rr,c:cc}],captures:[],capturedKings:0,capture:false})}}}return out}
function apply(board,m){const b=clone(board),p={...b[m.from.r][m.from.c]};b[m.from.r][m.from.c]=null;for(const x of m.captures)b[x.r][x.c]=null;b[m.to.r][m.to.c]=p;let promoted=false;if(!p.king&&((p.player==="white"&&m.to.r===0)||(p.player==="black"&&m.to.r===7))){p.king=true;b[m.to.r][m.to.c]=p;promoted=true}return{board:b,promoted}}
function count(player){let men=0,kings=0;for(const row of state.board)for(const p of row)if(p?.player===player)p.king?kings++:men++;return{men,kings,total:men+kings}}
function hash(board,turn){return turn+":"+board.map(row=>row.map(p=>!p?".":p.player[0]+(p.king?"K":"m")).join("")).join("")}
function sqnum(r,c){return r*4+Math.floor(c/2)+1}
function notation(m){return m.path.map(x=>sqnum(x.r,x.c)).join(m.capture?"x":"-")}
function snapshot(){return{board:clone(state.board),turn:state.turn,moves:state.moves.map(x=>({...x})),halfmove:state.halfmove,reps:{...state.reps},result:state.result}}
function restore(s){state.board=clone(s.board);state.turn=s.turn;state.moves=s.moves;state.halfmove=s.halfmove;state.reps=s.reps;state.result=s.result;state.selected=null;state.prefix=[];state.candidates=[];state.thinking=false}
function beep(kind){if(!state.sound)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.connect(g);g.connect(audioCtx.destination);o.type="sine";o.frequency.value=kind==="capture"?190:kind==="win"?620:330;g.gain.setValueAtTime(.035,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.09);o.start();o.stop(audioCtx.currentTime+.1)}catch{}}
function toast(t){const x=document.createElement("div");x.className="toast";x.textContent=t;$("#toastStack").appendChild(x);setTimeout(()=>x.remove(),1700)}
function displayToLogical(dr,dc){return state.human==="white"?{r:dr,c:dc}:{r:7-dr,c:7-dc}}
function logicalToDisplay(r,c){return state.human==="white"?{r,c}:{r:7-r,c:7-c}}
function prefixMatch(m,prefix){return prefix.every((x,i)=>m.path[i]&&m.path[i].r===x.r&&m.path[i].c===x.c)}
function nextDestinations(){if(!state.selected)return[];const i=state.prefix.length;const map=new Map();for(const m of state.candidates){const x=m.path[i];if(x)map.set(x.r+","+x.c,x)}return[...map.values()]}
function renderBoard(){boardEl.innerHTML="";const legal=!state.result&&state.turn===state.human&&!state.thinking?legalMoves(state.board,state.human):[];const origins=new Set(legal.map(m=>m.from.r+","+m.from.c)),dests=new Set(nextDestinations().map(x=>x.r+","+x.c));for(let dr=0;dr<N;dr++)for(let dc=0;dc<N;dc++){const{r,c}=displayToLogical(dr,dc),s=document.createElement("button");s.type="button";s.className="square"+(playable(r,c)?"":" dark");s.dataset.r=r;s.dataset.c=c;s.setAttribute("aria-label",`Casilla ${r+1},${c+1}`);if(origins.has(r+","+c))s.classList.add("legal-origin");if(dests.has(r+","+c))s.classList.add("destination");if(state.selected?.r===r&&state.selected?.c===c)s.classList.add("selected");const p=state.board[r][c];if(p){const d=document.createElement("span");d.className="piece "+p.player+(p.king?" king":"");s.appendChild(d)}boardEl.appendChild(s)}}
function renderMoves(){if(!state.moves.length){moveList.innerHTML='<div class="empty-log">La partida aún no ha dejado marcas.<br>La primera diagonal aparecerá aquí.</div>';return}moveList.innerHTML="";for(let i=0;i<state.moves.length;i+=2){const row=document.createElement("div");row.className="move-row";row.innerHTML=`<div class="move-index">${i/2+1}</div>`;for(let j=0;j<2;j++){const m=state.moves[i+j],cell=document.createElement("div");cell.className="move-cell"+(m?.capture?" capture":"")+((i+j===state.moves.length-1)?" latest":"");cell.textContent=m?m.text:"";row.appendChild(cell)}moveList.appendChild(row)}moveList.scrollTop=moveList.scrollHeight}
function render(){renderBoard();renderMoves();const h=count(state.human),a=count(state.ai),hv=h.men+h.kings*2.8,av=a.men+a.kings*2.8,pct=hv+av?100*hv/(hv+av):50;$("#humanPieceCount").textContent=h.total;$("#aiPieceCount").textContent=a.total;$("#balanceHuman").style.width=pct+"%";$(".balance-meter").setAttribute("aria-valuenow",Math.round(pct));$("#humanColorLabel").textContent=state.human==="white"?"Marfil":"Tinta";$("#aiColorLabel").textContent=state.ai==="white"?"Marfil":"Tinta";$("#humanMiniPiece").classList.toggle("dark",state.human==="black");$("#aiMiniPiece").classList.toggle("dark",state.ai==="black");$("#humanCard").classList.toggle("is-active",state.turn===state.human&&!state.result);$("#aiCard").classList.toggle("is-active",state.turn===state.ai&&!state.result);$("#moveCountLabel").textContent=state.moves.length+" jugadas";$("#orientationLabel").textContent=(state.human==="white"?"Marfil":"Tinta")+" abajo · notación 1–32";$("#aiDepthLabel").textContent=LEVELS[state.difficulty].label+(state.stats?` · d${state.stats.depth}`:" · adaptativa");undoButton.disabled=!state.history.length||state.thinking;$$('[data-side]').forEach(b=>b.classList.toggle("is-selected",b.dataset.side===state.human));$$('[data-level]').forEach(b=>b.classList.toggle("is-selected",b.dataset.level===state.difficulty));soundSwitch.setAttribute("aria-checked",String(state.sound));statusPanel.classList.toggle("is-thinking",state.thinking);if(state.result){statusLabel.textContent="Fin";statusTitle.textContent=state.result.draw?"Tablas":state.result.winner===state.human?"Victoria":"La IA gana";statusDetail.textContent=state.result.reason}else if(state.thinking){statusLabel.textContent="Cálculo";statusTitle.textContent="La IA piensa";statusDetail.textContent=state.stats?`${state.stats.nodes.toLocaleString("es-ES")} nodos · profundidad ${state.stats.depth}`:"Explorando diagonales…"}else if(state.turn===state.human){const legal=legalMoves(state.board,state.human),cap=legal[0]?.capture;statusLabel.textContent="En juego";statusTitle.textContent=cap?"Captura obligatoria":"Tu turno";statusDetail.textContent=state.selected?"Completa la diagonal marcada.":cap?"Sólo están activas las piezas que cumplen cantidad y calidad.":"Elige una ficha marcada y un destino rojo."}else{statusLabel.textContent="En juego";statusTitle.textContent="Turno rival";statusDetail.textContent="La IA prepara su respuesta."}}
function pips(){const h=12-count(state.ai).total,a=12-count(state.human).total;for(const[id,n,cls]of[["#humanCaptures",h,""],["#aiCaptures",a," ai-capture"]]){$(id).innerHTML="";for(let i=0;i<12;i++){const x=document.createElement("i");x.className="pip"+cls+(i<n?" filled":"");$(id).appendChild(x)}}}
function finishCheck(last){const enemy=opp(last),lm=legalMoves(state.board,enemy);if(!lm.length){state.result={winner:last,reason:count(enemy).total?"El rival no dispone de ningún movimiento legal.":"El rival se ha quedado sin piezas."};return true}if(state.halfmove>=80){state.result={draw:true,reason:"40 movimientos sin captura ni avance de peón."};return true}const h=hash(state.board,state.turn),n=(state.reps[h]||0)+1;state.reps[h]=n;if(n>=3){state.result={draw:true,reason:"Triple repetición de la posición."};return true}return false}
function commit(m,mover){state.history.push(snapshot());const moving=state.board[m.from.r][m.from.c],wasMan=moving&&!moving.king,{board,promoted}=apply(state.board,m);state.board=board;state.moves.push({text:notation(m)+(promoted?"=D":""),capture:m.capture,mover});state.halfmove=(m.capture||wasMan)?0:state.halfmove+1;state.turn=opp(mover);state.selected=null;state.prefix=[];state.candidates=[];beep(m.capture?"capture":"move");finishCheck(mover);pips();render();if(state.result)showEnd();else if(state.turn===state.ai)scheduleAI()}
function clickSquare(e){if(state.result||state.thinking||state.turn!==state.human)return;const s=e.target.closest(".square");if(!s)return;const r=+s.dataset.r,c=+s.dataset.c,legal=legalMoves(state.board,state.human);if(!state.selected){const cs=legal.filter(m=>m.from.r===r&&m.from.c===c);if(cs.length){state.selected={r,c};state.prefix=[{r,c}];state.candidates=cs;beep("move");render()}return}const next=nextDestinations(),hit=next.some(x=>x.r===r&&x.c===c);if(hit){state.prefix.push({r,c});state.candidates=state.candidates.filter(m=>prefixMatch(m,state.prefix));const complete=state.candidates.filter(m=>m.path.length===state.prefix.length);const continuing=state.candidates.some(m=>m.path.length>state.prefix.length);if(complete.length&&!continuing){commit(complete[0],state.human);return}render();return}const cs=legal.filter(m=>m.from.r===r&&m.from.c===c);if(cs.length){state.selected={r,c};state.prefix=[{r,c}];state.candidates=cs;render()}else{state.selected=null;state.prefix=[];state.candidates=[];render()}}
function evaluate(board,ai){let v=0;for(let r=0;r<N;r++)for(let c=0;c<N;c++){const p=board[r][c];if(!p)continue;const sign=p.player===ai?1:-1,adv=p.player==="white"?7-r:r,center=3.5-(Math.abs(r-3.5)+Math.abs(c-3.5))/2;v+=sign*((p.king?330:100)+(p.king?center*6:adv*7+center*3))}return v}
function aiMove(){const cfg=LEVELS[state.difficulty],start=performance.now();let nodes=0;function search(board,turn,depth,a,b){nodes++;const moves=legalMoves(board,turn);if(!moves.length)return turn===state.ai?-100000-depth:100000+depth;if(depth<=0)return evaluate(board,state.ai);moves.sort((x,y)=>(y.capture?100+y.captures.length:0)-(x.capture?100+x.captures.length:0));if(turn===state.ai){let best=-Infinity;for(const m of moves){best=Math.max(best,search(apply(board,m).board,opp(turn),depth-1,a,b));a=Math.max(a,best);if(a>=b)break}return best}else{let best=Infinity;for(const m of moves){best=Math.min(best,search(apply(board,m).board,opp(turn),depth-1,a,b));b=Math.min(b,best);if(a>=b)break}return best}}const moves=legalMoves(state.board,state.ai),scored=[];for(const m of moves)scored.push({m,s:search(apply(state.board,m).board,state.human,cfg.depth-1,-Infinity,Infinity)});scored.sort((x,y)=>y.s-x.s);let pick=scored[0];if(cfg.noise&&scored.length>1&&Math.random()<cfg.noise)pick=scored[Math.min(scored.length-1,1+Math.floor(Math.random()*2))];return{move:pick?.m,depth:cfg.depth,nodes,ms:Math.round(performance.now()-start)}}
function scheduleAI(){state.thinking=true;render();setTimeout(()=>{if(state.result||state.turn!==state.ai)return;const result=aiMove();state.stats=result;state.thinking=false;if(result.move)commit(result.move,state.ai);else{state.result={winner:state.human,reason:"La IA no dispone de movimiento legal."};render();showEnd()}},260)}
function newGame(h=state.human){const difficulty=state.difficulty,sound=state.sound;state=fresh(h,difficulty);state.sound=sound;pips();render();toast(h==="white"?"Marfil abre la partida.":"La IA abre con marfil.");if(state.turn===state.ai)scheduleAI()}
function undo(){if(state.thinking||!state.history.length)return;let idx=-1;for(let i=state.history.length-1;i>=0;i--)if(state.moves[i]?.mover===state.human){idx=i;break}if(idx<0)return;restore(state.history[idx]);state.history=state.history.slice(0,idx);pips();render();toast("Turno recuperado.")}
function showEnd(){const title=$("#gameOverTitle"),detail=$("#gameOverDetail");title.textContent=state.result.draw?"Tablas.":state.result.winner===state.human?"Victoria.":"La IA gana.";detail.textContent=state.result.reason;beep(state.result.winner===state.human?"win":"move");if(!gameOverDialog.open)gameOverDialog.showModal()}
boardEl.addEventListener("click",clickSquare);$("#newGameButton").addEventListener("click",()=>newGame());undoButton.addEventListener("click",undo);$$('[data-side]').forEach(b=>b.addEventListener("click",()=>newGame(b.dataset.side)));$$('[data-level]').forEach(b=>b.addEventListener("click",()=>{state.difficulty=b.dataset.level;render();toast(`IA en nivel ${LEVELS[state.difficulty].label}.`)}));soundSwitch.addEventListener("click",()=>{state.sound=!state.sound;render();beep("move")});$$('[data-dialog]').forEach(b=>b.addEventListener("click",()=>$("#"+b.dataset.dialog+"Dialog").showModal()));$$('dialog .dialog-close').forEach(b=>b.addEventListener("click",()=>b.closest("dialog").close()));$("#rematchButton").addEventListener("click",()=>{gameOverDialog.close();newGame(state.human)});$("#swapSideButton").addEventListener("click",()=>{gameOverDialog.close();newGame(opp(state.human))});document.addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="z"){e.preventDefault();undo()}if(e.key==="Escape"&&state.selected){state.selected=null;state.prefix=[];state.candidates=[];render()}});pips();render();
})();