#!/usr/bin/env python3
"""Prepare full-length CC0 tracks with Tindrop's canonical Dart cue engine."""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import urllib.parse
from pathlib import Path

from catalog_cue_analyzer import canonical_beat_map, preview_start


MEDIA_ROOT = "https://media.lagartijalabs.com/tindrop/music/v1"
CC0_URL = "https://creativecommons.org/publicdomain/zero/1.0/"
MOBILE_BITRATE = "128k"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def download(track: dict, destination: Path) -> None:
    if destination.is_file() and sha256(destination) == track["sourceSha256"]:
        return
    temporary = destination.with_suffix(destination.suffix + ".part")
    subprocess.run(
        [
            "curl",
            "--fail",
            "--location",
            "--silent",
            "--show-error",
            "--user-agent",
            "Tindrop catalog preparation/1.0",
            "--output",
            str(temporary),
            track["sourceUrl"],
        ],
        check=True,
    )
    if sha256(temporary) != track["sourceSha256"]:
        temporary.unlink(missing_ok=True)
        raise ValueError(
            f"{track['id']}: downloaded source hash does not match evidence"
        )
    temporary.replace(destination)


def encode(source: Path, output: Path, track: dict) -> None:
    subprocess.run(
        [
            "ffmpeg",
            "-hide_banner",
            "-loglevel",
            "error",
            "-y",
            "-i",
            str(source),
            "-map_metadata",
            "-1",
            "-af",
            "loudnorm=I=-16:TP=-1.5:LRA=11",
            "-ar",
            "44100",
            "-ac",
            "2",
            "-c:a",
            "aac",
            "-profile:a",
            "aac_low",
            "-b:a",
            MOBILE_BITRATE,
            "-movflags",
            "+faststart",
            "-metadata",
            f"title={track['title']}",
            "-metadata",
            f"artist={track['artist']}",
            str(output),
        ],
        check=True,
    )


def duration_ms(path: Path) -> int:
    result = subprocess.run(
        [
            "ffprobe",
            "-v",
            "error",
            "-show_entries",
            "format=duration",
            "-of",
            "default=noprint_wrappers=1:nokey=1",
            str(path),
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    return round(float(result.stdout.strip()) * 1000)


def write_evidence(root: Path, track: dict, encoded: Path) -> None:
    (root / "licenses" / f"{track['id']}.md").write_text(
        f"# {track['title']}\n\n"
        f"- Artist/rightsholder: {track['artist']}\n"
        "- Catalog license ID: `CC0-1.0`\n"
        f"- Individual source and license evidence: {track['sourcePage']}\n"
        f"- CC0 legal tool: {CC0_URL}\n"
        f"- Original download URL: {track['sourceUrl']}\n"
        f"- Original download SHA-256: `{track['sourceSha256']}`\n"
        f"- Tindrop mobile derivative SHA-256: `{sha256(encoded)}`\n"
        f"- Mobile preparation: complete song, normalized to -16 LUFS and encoded as AAC-LC {MOBILE_BITRATE}; no editorial excerpt or added samples.\n"
        "- Cue preparation: full-track `BeatMap` generated by Tindrop's canonical Dart analyzer, identical to imported user audio.\n"
        "- Attribution: not legally required by CC0, but Tindrop displays the artist voluntarily.\n"
        "- Verification: preserve this record and the exact source hash with repository history.\n",
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    root = Path(__file__).resolve().parent
    parser.add_argument(
        "--artifacts",
        type=Path,
        default=root.parent.parent / ".artifacts" / "tindrop_music_cc0_v2",
    )
    parser.add_argument("--catalog", type=Path, default=root / "catalog.local.json")
    parser.add_argument("--tracks", type=Path, default=root / "cc0_tracks.json")
    parser.add_argument("--tindrop-root", type=Path, required=True)
    parser.add_argument("--issued-at-ms", type=int, required=True)
    parser.add_argument("--reuse-encoded", action="store_true")
    args = parser.parse_args()
    tracks = json.loads(args.tracks.read_text(encoding="utf-8"))
    payload = json.loads(args.catalog.read_text(encoding="utf-8"))
    # The curated CC0 manifest is authoritative. Rebuilding from it deliberately
    # drops proprietary or retired tracks instead of carrying stale catalog
    # entries forward from the previous signed payload.
    existing: dict[str, dict] = {}
    source_root = args.artifacts / "sources"
    encoded_root = args.artifacts / "encoded"
    source_root.mkdir(parents=True, exist_ok=True)
    encoded_root.mkdir(parents=True, exist_ok=True)
    for track in tracks:
        extension = Path(urllib.parse.urlparse(track["sourceUrl"]).path).suffix
        source = source_root / f"{track['id']}{extension or '.audio'}"
        encoded = encoded_root / f"{track['id']}.m4a"
        download(track, source)
        if not args.reuse_encoded or not encoded.is_file():
            encode(source, encoded, track)
        total_ms = duration_ms(encoded)
        beat_map = canonical_beat_map(encoded, total_ms, args.tindrop_root)
        existing[track["id"]] = {
            "id": track["id"],
            "title": track["title"],
            "artist": track["artist"],
            "audioUrl": f"{MEDIA_ROOT}/{track['id']}.m4a",
            "durationMs": total_ms,
            "sizeBytes": encoded.stat().st_size,
            "sha256": sha256(encoded),
            "licenseId": "CC0-1.0",
            "licenseUrl": CC0_URL,
            "sortOrder": track["sortOrder"],
            "previewStartMs": preview_start(beat_map, total_ms),
            "featured": track["featured"],
            "beatMap": beat_map,
        }
        write_evidence(root, track, encoded)
        print(
            f"prepared {track['id']}: {total_ms / 1000:.1f}s, "
            f"{encoded.stat().st_size / 1024 / 1024:.2f} MiB, "
            f"{beat_map['bpm']:.1f} BPM, {beat_map['confidence']} confidence",
            flush=True,
        )
    payload["version"] = max(3, int(payload.get("version", 1)))
    payload["issuedAtMs"] = args.issued_at_ms
    payload["tracks"] = sorted(existing.values(), key=lambda track: track["sortOrder"])
    args.catalog.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
